const DigitMaskData = [
  {
    "S7": null,
    "S11": null,
    "S5": null,
    "S10": null,
    "S13": null,
    "S6": null,
    "S3": null,
    "S9": null,
    "S4": null,
    "S2": null,
    "S1": null,
    "S8": null,
    "S12": null,
    "S14": "E",
    "D12D11": 0,
    "Mask": 0
  },
  {
    "S7": null,
    "S11": null,
    "S5": null,
    "S10": null,
    "S13": null,
    "S6": null,
    "S3": null,
    "S9": null,
    "S4": null,
    "S2": null,
    "S1": null,
    "S8": null,
    "S12": null,
    "S14": "E",
    "D12D11": 0,
    "Mask": 1
  },
  {
    "S7": null,
    "S11": null,
    "S5": null,
    "S10": null,
    "S13": null,
    "S6": null,
    "S3": null,
    "S9": null,
    "S4": null,
    "S2": null,
    "S1": null,
    "S8": "E",
    "S12": "E",
    "S14": "E",
    "D12D11": 0,
    "Mask": 2
  },
  {
    "S7": null,
    "S11": null,
    "S5": null,
    "S10": null,
    "S13": null,
    "S6": null,
    "S3": null,
    "S9": null,
    "S4": null,
    "S2": null,
    "S1": "E",
    "S8": "E",
    "S12": "E",
    "S14": "E",
    "D12D11": 0,
    "Mask": 3
  },
  {
    "S7": null,
    "S11": null,
    "S5": null,
    "S10": null,
    "S13": null,
    "S6": null,
    "S3": null,
    "S9": null,
    "S4": null,
    "S2": null,
    "S1": "E",
    "S8": "E",
    "S12": "E",
    "S14": null,
    "D12D11": 0,
    "Mask": 4
  },
  {
    "S7": null,
    "S11": null,
    "S5": null,
    "S10": null,
    "S13": null,
    "S6": null,
    "S3": null,
    "S9": null,
    "S4": null,
    "S2": null,
    "S1": null,
    "S8": "E",
    "S12": "E",
    "S14": "E",
    "D12D11": 0,
    "Mask": 5
  },
  {
    "S7": null,
    "S11": "E",
    "S5": null,
    "S10": null,
    "S13": null,
    "S6": null,
    "S3": null,
    "S9": null,
    "S4": null,
    "S2": null,
    "S1": null,
    "S8": null,
    "S12": null,
    "S14": null,
    "D12D11": 1,
    "Mask": 0
  },
  {
    "S7": null,
    "S11": "E",
    "S5": null,
    "S10": null,
    "S13": null,
    "S6": null,
    "S3": null,
    "S9": null,
    "S4": null,
    "S2": null,
    "S1": null,
    "S8": null,
    "S12": null,
    "S14": null,
    "D12D11": 1,
    "Mask": 1
  },
  {
    "S7": "E",
    "S11": "E",
    "S5": "E",
    "S10": "E",
    "S13": "E",
    "S6": "E",
    "S3": "E",
    "S9": "E",
    "S4": "E",
    "S2": "E",
    "S1": "E",
    "S8": "E",
    "S12": "E",
    "S14": "E",
    "D12D11": 1,
    "Mask": 2
  },
  {
    "S7": "E",
    "S11": "E",
    "S5": "E",
    "S10": "E",
    "S13": "E",
    "S6": "E",
    "S3": "E",
    "S9": "E",
    "S4": "E",
    "S2": "E",
    "S1": "E",
    "S8": "E",
    "S12": "E",
    "S14": "E",
    "D12D11": 1,
    "Mask": 3
  },
  {
    "S7": "E",
    "S11": "E",
    "S5": "E",
    "S10": "E",
    "S13": "E",
    "S6": "E",
    "S3": "E",
    "S9": "E",
    "S4": "E",
    "S2": "E",
    "S1": "E",
    "S8": "E",
    "S12": "E",
    "S14": null,
    "D12D11": 1,
    "Mask": 4
  },
  {
    "S7": "E",
    "S11": "E",
    "S5": "E",
    "S10": "E",
    "S13": "E",
    "S6": "E",
    "S3": "E",
    "S9": "E",
    "S4": "E",
    "S2": "E",
    "S1": "E",
    "S8": "E",
    "S12": "E",
    "S14": "E",
    "D12D11": 1,
    "Mask": 5
  },
  {
    "S7": "E",
    "S11": null,
    "S5": null,
    "S10": null,
    "S13": null,
    "S6": null,
    "S3": null,
    "S9": null,
    "S4": null,
    "S2": null,
    "S1": null,
    "S8": null,
    "S12": null,
    "S14": null,
    "D12D11": 2,
    "Mask": 0
  },
  {
    "S7": "E",
    "S11": null,
    "S5": null,
    "S10": null,
    "S13": null,
    "S6": null,
    "S3": null,
    "S9": null,
    "S4": null,
    "S2": null,
    "S1": null,
    "S8": null,
    "S12": null,
    "S14": null,
    "D12D11": 2,
    "Mask": 1
  }
];