const DigitMaskHeaders = {
  "S7": 0,
  "S11": 1,
  "S5": 2,
  "S10": 3,
  "S13": 4,
  "S6": 5,
  "S3": 6,
  "S9": 7,
  "S4": 8,
  "S2": 9,
  "S1": 10,
  "S8": 11,
  "S12": 12,
  "S14": 13,
  "D12D11": 14,
  "Mask": 15
};

const DigitMaskData = [
  [null, null, null, null, null, null, null, null, null, null, null, null, null,  "E", 0, 0],
  [null, null, null, null, null, null, null, null, null, null, null, null, null,  "E", 0, 1],
  [null, null, null, null, null, null, null, null, null, null, null,  "E",  "E",  "E", 0, 2],
  [null, null, null, null, null, null, null, null, null, null,  "E",  "E",  "E",  "E", 0, 3],
  [null, null, null, null, null, null, null, null, null, null,  "E",  "E",  "E", null, 0, 4],
  [null, null, null, null, null, null, null, null, null, null, null,  "E",  "E",  "E", 0, 5],
  [null,  "E", null, null, null, null, null, null, null, null, null, null, null, null, 1, 0],
  [null,  "E", null, null, null, null, null, null, null, null, null, null, null, null, 1, 1],
  [ "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E", 1, 2],
  [ "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E", 1, 3],
  [ "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E", null, 1, 4],
  [ "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E", 1, 5],
  [ "E", null, null, null, null, null, null, null, null, null, null, null, null, null, 2, 0],
  [ "E", null, null, null, null, null, null, null, null, null, null, null, null, null, 2, 1],
  [null,  "E",  "E", null, null, null, null, null, null, null, null, null, null, null, 2, 2],
  [ "E", null, null, null, null, null, null, null, null, null, null, null, null, null, 2, 3],
  [ "E", null, null, null, null, null, null, null, null, null, null, null, null, null, 2, 4],
  [ "E", null, null, null, null, null, null, null, null, null, null, null, null, null, 2, 5],
  [null, null, null, null, null, null, null, null, null, null,  "E", null, null, null, 3, 0],
  [null, null, null, null, null, null, null, null, null, null,  "E", null, null, null, 3, 1],
  [null, null, null, null, null, null, null, null, null,  "E", null, null, null, null, 3, 2],
  [ "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E", null, null, null, 3, 3],
  [ "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E", null, null, null, null, 3, 4],
  [null,  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E",  "E", null, null, null, 3, 5]
];
